### ISSUE TITLE
✨ feat : 로그인한 유저일 경우 랜딩을 거치지 않고 대시보드 페이지로 리다이렉트

### ISSUE THREAD

**Issue by Haze-S** [Sprint-Part3-14Team/14team-project#38]
## 📝설명
로그인 한 유저일 경우 루트 url로 접속하더라도 대시보드로 바로 이동됩니다.

## ✅TO-DO
- 페이지 리다이렉트
- 로그아웃 했을 때 다시 랜딩으로 가는 로직 구현 (논의 필요)

**Comment by CitrusSoda** [comment]
오 #22 로 따로 만들었는데 먼저 대시보드만 하시나요??

**Comment by Haze-S** [comment]
> 오 #22 로 따로 만들었는데 먼저 대시보드만 하시나요??

아, #22 하나로 진행하면 되겠네요!! 해당 이슈는 닫겠습니다
